// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the Wails service entrypoint.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./models/models.js";

export function ExportToDesktop(content: string): $CancellablePromise<string> {
    return $Call.ByID(94639756, content);
}

export function GenerateMetaYAML(req: models$0.GenerateMetaYAMLRequest): $CancellablePromise<string> {
    return $Call.ByID(407915414, req);
}

export function GetUpdateStatus(): $CancellablePromise<models$0.UpdateStatus> {
    return $Call.ByID(1444054506).then(($result: any) => {
        return $$createType0($result);
    });
}

export function LoadServiceTree(): $CancellablePromise<models$0.ServiceTree[]> {
    return $Call.ByID(822027430).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ParseLinks(input: string): $CancellablePromise<models$0.ParseReport> {
    return $Call.ByID(146865531, input).then(($result: any) => {
        return $$createType3($result);
    });
}

export function StartUpdateCheck(): $CancellablePromise<models$0.UpdateStatus> {
    return $Call.ByID(3693088476).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.UpdateStatus.createFrom;
const $$createType1 = models$0.ServiceTree.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = models$0.ParseReport.createFrom;
