// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class GenerateMetaYAMLRequest {
    "nodes": ProxyNode[];
    "selectedNodeIds": string[];
    "directCidrs": string[];
    "selections": ServiceSelection[];
    "mode": ParseMode;
    "proxyGroupName": string;
    "servicesSnapshot": ServiceTree[];

    /** Creates a new GenerateMetaYAMLRequest instance. */
    constructor($$source: Partial<GenerateMetaYAMLRequest> = {}) {
        if (!("nodes" in $$source)) {
            this["nodes"] = [];
        }
        if (!("selectedNodeIds" in $$source)) {
            this["selectedNodeIds"] = [];
        }
        if (!("directCidrs" in $$source)) {
            this["directCidrs"] = [];
        }
        if (!("selections" in $$source)) {
            this["selections"] = [];
        }
        if (!("mode" in $$source)) {
            this["mode"] = ParseMode.$zero;
        }
        if (!("proxyGroupName" in $$source)) {
            this["proxyGroupName"] = "";
        }
        if (!("servicesSnapshot" in $$source)) {
            this["servicesSnapshot"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GenerateMetaYAMLRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GenerateMetaYAMLRequest {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType4;
        const $$createField6_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField0_0($$parsedSource["nodes"]);
        }
        if ("selectedNodeIds" in $$parsedSource) {
            $$parsedSource["selectedNodeIds"] = $$createField1_0($$parsedSource["selectedNodeIds"]);
        }
        if ("directCidrs" in $$parsedSource) {
            $$parsedSource["directCidrs"] = $$createField2_0($$parsedSource["directCidrs"]);
        }
        if ("selections" in $$parsedSource) {
            $$parsedSource["selections"] = $$createField3_0($$parsedSource["selections"]);
        }
        if ("servicesSnapshot" in $$parsedSource) {
            $$parsedSource["servicesSnapshot"] = $$createField6_0($$parsedSource["servicesSnapshot"]);
        }
        return new GenerateMetaYAMLRequest($$parsedSource as Partial<GenerateMetaYAMLRequest>);
    }
}

export class ParseIssue {
    "protocol": string;
    "field": string;
    "message": string;

    /** Creates a new ParseIssue instance. */
    constructor($$source: Partial<ParseIssue> = {}) {
        if (!("protocol" in $$source)) {
            this["protocol"] = "";
        }
        if (!("field" in $$source)) {
            this["field"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ParseIssue instance from a string or object.
     */
    static createFrom($$source: any = {}): ParseIssue {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ParseIssue($$parsedSource as Partial<ParseIssue>);
    }
}

export enum ParseMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ModeWhitelist = "whitelist",
    ModeBlacklist = "blacklist",
};

export class ParseReport {
    "nodes": ProxyNode[];
    "errors": ParseIssue[];

    /** Creates a new ParseReport instance. */
    constructor($$source: Partial<ParseReport> = {}) {
        if (!("nodes" in $$source)) {
            this["nodes"] = [];
        }
        if (!("errors" in $$source)) {
            this["errors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ParseReport instance from a string or object.
     */
    static createFrom($$source: any = {}): ParseReport {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField0_0($$parsedSource["nodes"]);
        }
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField1_0($$parsedSource["errors"]);
        }
        return new ParseReport($$parsedSource as Partial<ParseReport>);
    }
}

export enum Protocol {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ProtocolVLESS = "vless",
    ProtocolTUIC = "tuic",
    ProtocolHysteria = "hysteria2",
    ProtocolSS = "ss",
    ProtocolTrojan = "trojan",
    ProtocolVMess = "vmess",
};

export class ProxyNode {
    "id": string;
    "name": string;
    "protocol": Protocol;
    "server": string;
    "port": number;
    "uuid"?: string;
    "token"?: string;
    "password"?: string;
    "cipher"?: string;
    "plugin"?: string;
    "pluginOpts"?: string;
    "network"?: string;
    "tls"?: boolean;
    "sni"?: string;
    "alpn"?: string;
    "flow"?: string;
    "security"?: string;
    "publicKey"?: string;
    "shortId"?: string;
    "fingerprint"?: string;
    "serviceName"?: string;
    "host"?: string;
    "path"?: string;
    "congestionControl"?: string;
    "udpRelayMode"?: string;
    "dialerProxy"?: string;
    "rawLink": string;
    "issues"?: ParseIssue[];

    /** Creates a new ProxyNode instance. */
    constructor($$source: Partial<ProxyNode> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("protocol" in $$source)) {
            this["protocol"] = Protocol.$zero;
        }
        if (!("server" in $$source)) {
            this["server"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("rawLink" in $$source)) {
            this["rawLink"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyNode instance from a string or object.
     */
    static createFrom($$source: any = {}): ProxyNode {
        const $$createField27_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("issues" in $$parsedSource) {
            $$parsedSource["issues"] = $$createField27_0($$parsedSource["issues"]);
        }
        return new ProxyNode($$parsedSource as Partial<ProxyNode>);
    }
}

export class ServiceSelection {
    "serviceId": string;
    "policy": string;
    "enabled": boolean;

    /** Creates a new ServiceSelection instance. */
    constructor($$source: Partial<ServiceSelection> = {}) {
        if (!("serviceId" in $$source)) {
            this["serviceId"] = "";
        }
        if (!("policy" in $$source)) {
            this["policy"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServiceSelection instance from a string or object.
     */
    static createFrom($$source: any = {}): ServiceSelection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServiceSelection($$parsedSource as Partial<ServiceSelection>);
    }
}

export class ServiceTree {
    "id": string;
    "name": string;
    "kind": string;
    "provider"?: string;
    "ruleType"?: string;
    "domains"?: string[];
    "keywords"?: string[];
    "ipCidrs"?: string[];
    "defaultOut"?: string;
    "children"?: ServiceTree[];

    /** Creates a new ServiceTree instance. */
    constructor($$source: Partial<ServiceTree> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServiceTree instance from a string or object.
     */
    static createFrom($$source: any = {}): ServiceTree {
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType2;
        const $$createField7_0 = $$createType2;
        const $$createField9_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("domains" in $$parsedSource) {
            $$parsedSource["domains"] = $$createField5_0($$parsedSource["domains"]);
        }
        if ("keywords" in $$parsedSource) {
            $$parsedSource["keywords"] = $$createField6_0($$parsedSource["keywords"]);
        }
        if ("ipCidrs" in $$parsedSource) {
            $$parsedSource["ipCidrs"] = $$createField7_0($$parsedSource["ipCidrs"]);
        }
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField9_0($$parsedSource["children"]);
        }
        return new ServiceTree($$parsedSource as Partial<ServiceTree>);
    }
}

// Private type creation functions
const $$createType0 = ProxyNode.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = ServiceSelection.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = ServiceTree.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = ParseIssue.createFrom;
const $$createType8 = $Create.Array($$createType7);
